### ISSUE TITLE
Prism doesn't work. ( hexo-prism-plugin 2.0 )

### ISSUE THREAD

**Issue by cubesky** [ele828/hexo-prism-plugin#11]
![image](https://cloud.githubusercontent.com/assets/8038511/23116595/44db43e0-f786-11e6-914e-ad5bec255691.png)

I just update `hexo-prism-plugin` version `2.0` , and I run it as `hexo clean&hexo s`. But it still doesn't work.

**Comment by cubesky** [comment]
![image](https://cloud.githubusercontent.com/assets/8038511/23116709/fd097fcc-f786-11e6-9f2f-325628bb3c54.png)

**Comment by cubesky** [comment]
And the padding style of `line-number` always override by theme.

**Comment by cubesky** [comment]
![image](https://cloud.githubusercontent.com/assets/8038511/23116774/570c85f0-f787-11e6-815e-2f4d86af2abd.png)

I just test for hexo build-in theme `landscape`. This plugin doesn't work too.

**Comment by cubesky** [comment]
![image](https://cloud.githubusercontent.com/assets/8038511/23116883/e9f63b54-f787-11e6-9c74-ed2cb0774d3a.png)

I saw `dockerfile` is support by `prism.js`

**Comment by ele828** [comment]
@cubesky actually it works. But you didn't specify the right language for Prism.js.

I suppose in your case it should be `docker` in your markdown file instead of `dockerfile`

You could find languages here http://prismjs.com/#languages-list

Thanks!

**Comment by cubesky** [comment]
Oh,Thank you.
That's my fault.
