### ISSUE TITLE
line_number not shown

### ISSUE THREAD

**Issue by cubesky** [ele828/hexo-prism-plugin#12]
I set `line_number` to `true` and line_number not work.

See https://liyin.date/2017/01/21/Minecraft-with-Docker/

**Comment by neoFelhz** [comment]
I think we should patch the css about linenumber to fix it.
This is demo after my patch.
https://blog.neofelhz.space/archives/coding-snapdragon-810-down.html

**Comment by ele828** [comment]
@cubesky Actually I don't have time to look into this now.

@neoFelhz I would really appreciate it if you could send us a pull request about that patch :) thanks!

**Comment by neoFelhz** [comment]
@ele828 
![](https://cloud.githubusercontent.com/assets/8038511/23035834/7d5b5d7c-f4bb-11e6-9227-2a30254b59b7.png)

The idea comes from @cubesky

**Comment by neoFelhz** [comment]
I think I should send the PR to `node-prismjs`. The bug is not caused by plugin it self, it caused by dependencies.

**Comment by ele828** [comment]
@neoFelhz  thanks for digging into this issue. It would be nice if you could make a pull request to fix it :)

**Comment by neoFelhz** [comment]
I have send a [PR](https://github.com/PrismJS/prism/pull/1105) to them right now. :)

**Comment by ele828** [comment]
@neoFelhz 👍
