### ISSUE TITLE
hexo error

### ISSUE THREAD

**Issue by yinhaojun** [ele828/hexo-prism-plugin#13]
INFO  Start processing
INFO  Files loaded in 671 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\blog\HaojunYinGeek.github.io\
node_modules\prismjs\themes\prism-realtime.css'
    at Error (native)

**Comment by ele828** [comment]
Did you upgrade to version 2.0.0?

**Comment by PolluxLee** [comment]
I have the same problem
