### ISSUE TITLE
建议可以自定义prism.js

### ISSUE THREAD

**Issue by time-river** [ele828/hexo-prism-plugin#2]
插件里面的 prism.js 太大了，影响加载速度，建议可以使用自己配置的 prism.js

**Comment by ele828** [comment]
你可以在Prism官网配置，然后直接替换这个文件的。

后面有时间的话，我会处理这个问题，另外欢迎PR！

**Comment by time-river** [comment]
今天尝试添加这个功能，但无法向 `source/js/` 内添加任何 js 文件，否则 `hexo server` 报错，不知道是否为使用的主题原因。

**Comment by ele828** [comment]
有报错的log信息吗？

**Comment by ele828** [comment]
建议升级到最新版本再重试一下 ：）
