### ISSUE TITLE
Failed to highlight C++ code

### ISSUE THREAD

**Issue by fengwang** [ele828/hexo-prism-plugin#23]
inserting cpp source code such like

```language-cpp
int function( double x )
{
    return std::floor( x );
}
```

but unfortunately the output code is not highlighted.

**Comment by ele828** [comment]
Hi, it works well in my local machine. Did you add cpp annotation to your markdown?
```
```cpp
int function( double x )
{
    return std::floor( x );
}
```
```

**Comment by fengwang** [comment]
@ele828 Thank you very much for your kind reply. I have  tried both

```
    ```language-cpp
    //my code
    ````
```
and 
```
    ```cpp
    //my code
    ````
```
but no luck.

In the `_config.xml` file, I have already set
```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
and 
```
prism_plugin:
    mode: 'realtime'
    theme: 'coy'
    line_number: true
```

One of the generated page demonstrating this problem is available at [this blog](http://fengwang.github.io/2017/06/02/std-optional-Maybe-Monad-in-C/)
