### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by unicornt** [ele828/hexo-prism-plugin#3]
if i move my blog to subdirectory,this plugin doesn't work anymore.

**Comment by ele828** [comment]
What do you mean by subdirectory? Can you show me the directory structure, so that I could fix this issue! thanks :)

**Comment by unicornt** [comment]
if i put my blog in unicornt.github.io,it works very well
but now i move my blog to unicornt.github.io/oi-blog,it doesn't work anymore

**Comment by ele828** [comment]
This plugin is based on hexo's base directory, if you want to move, you should move all of your hexo   folders and files to sub-folder. Then it should work I think.

**Comment by unicornt** [comment]
i just push my blog to the subdirectory,like this
deploy:
  type: git
  repository: https://github.com/unicornt/oi-blog.git
  brach: master

**Comment by unicornt** [comment]
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://unicornt.github.io/oi-blog
root: /oi-blog
permalink: :year/:month/:day/:title/
permalink_defaults:

**Comment by ele828** [comment]
Ok, I know what you mean. I'll try to fix it asap.

**Comment by ele828** [comment]
I fixed it, please update to version 1.0.2

**Comment by unicornt** [comment]
thank you
