### ISSUE TITLE
The highlight does not work

### ISSUE THREAD

**Issue by MrclSJ** [ele828/hexo-prism-plugin#33]
I followed the ReadMe.md and set the _config.yml
`
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess 
  theme: 'coy'
  line_number: false   # default false
  auto_import_assets: true
`

However, the code highlight does not shown and the theme also does not work.

**Comment by ywzhaiqi** [comment]
the same, not work. 

the result is raw.

```html
<pre><code class="javascript">
import { AppContainer } from 'react-hot-loader'
</code></pre>
```
