### ISSUE TITLE
Custom css doesn't work

### ISSUE THREAD

**Issue by bibixx** [ele828/hexo-prism-plugin#41]
So custom css doesn't work if I download package from npm. However when I install it directly from this repository all works.

What I have discovered is that probably there is wrong version published into npm since `src/index.js` in `node_modules` is different than one in this repository.

**Comment by ele828** [comment]
can you retry again, version 2.3.0? I just released new version.

**Comment by bibixx** [comment]
Yes! With version 2.3 it works great.
